#! /bin/bash
#
# maketables.sh
# Dowload list of public suffixes and create table.go from it
#

wget -O _table.tmp "http://mxr.mozilla.org/mozilla-central/source/netwerk/dns/effective_tld_names.dat?raw=1"
if test $? -ne 0; then
    echo "Could not download list"
    exit 1
fi

now=`date`

cat <<EOF > table.go
// Copyright 2012 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package cookiejar

// This file was generated by maketables.sh on $now
// Do not modify.

// A 'public suffix' is one under which Internet users can directly register
// names.  This list is maintained on http://publicsuffix.org/ 
// See there for a description of the format and further details.
// 
// A rule of the form "*.jp" forbidds domain cookies for any direct subdomain
// of jp _and_ for jp itself.  We add an explicit rule of the form "jp" in
// such a case to faciliate further processing.
// A rule of the form "!pref.kyoto.jp" is stored as {"jp", "kyoto", "!pref"}  .
// The list of rules must be sorted by tld.
var publicsuffixRules psStorage = [][]string{
EOF

gawk '/^\/\//{next} /^[ \t]*$/{next}{split($1,a,"\\."); if(a[1]=="*") {for(i=length(a); i>1; i--){printf "%s ", a[i]}; printf "\n"}; for(i=length(a); i>0; i--){printf "%s ", a[i]}; printf "\n" }' _table.tmp | sort | gawk '{printf "\t{"; for(i=1; i<=NF; i++) {printf "\"%s\", ", $i}; printf "},\n";}' >> table.go
echo "}" >> table.go
gofmt -w table.go

rm -f _table.tmp